---
abstract: 'Trivial File Transfer Protocol daemon'
author:
  - 'Jan Henning Thorsen, all rights reserved.'
build_requires:
  AnyEvent: 5.26
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-TFTPd
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent::Handle::UDP: 0.01
  Moose: 1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=AnyEvent-TFTPd
  homepage: http://search.cpan.org/dist/AnyEvent-TFTPd
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/anyevent-tftpd.git
version: 0.1301
